### ISSUE TITLE
robocopy.exe keeps running if the application is closed 

### ISSUE THREAD

**Issue by Slion** [tjscience/RoboSharp#65] opened 2018-08-29 09:15 UTC
Should we not kill robocopy when the RoboCommand object is destroyed or disposed?

**Comment by bruceburge** [comment] 2018-08-30 16:52
The short answer is yes, and in my experience RoboCopy executable does not persist after properly shutdown, so I would say there is likely something going on.

Can you give more specifics about how you are using robocopy? and what side effects you are seeing?

**Comment by tjscience** [comment] 2018-09-05 14:37
Hi @Slion, @bruceburge is right. the robocopy process should be killed upon shutdown of the application which is using the RoboSharp library. Do you have a sample app that can reproduce the issue, or any sample code?

**Comment by Slion** [comment] 2018-09-07 08:09
Here the function I'm using:

        /// <summary>
        /// Async file copy with progress report.
        /// </summary>
        /// <param name="sourcePath"></param>
        /// <param name="destinationPath"></param>
        /// <returns></returns>
        public async Task CopyFileAsync(string sourcePath, string destinationPath)
        {
            if (File.Exists(destinationPath))
            {
                // Do not overwrite and assume the file in place is the same
                return;
            }

            // Using robocopy through RoboSharp
            RoboCommand copy = new RoboCommand();
            // Set source directory
            copy.CopyOptions.Source = Path.GetDirectoryName(sourcePath);
            // Set destination directory
            copy.CopyOptions.Destination = Path.GetDirectoryName(destinationPath);
            // Set source file name
            copy.CopyOptions.FileFilter = Path.GetFileName(sourcePath);
            // Define retry parameters
            copy.RetryOptions.RetryCount = 10; // Retry N times
            copy.RetryOptions.RetryWaitTime = 2; // 2 seconds I guess
            // Hook in progress handler
            copy.OnCopyProgressChanged += FileCopyProgressHandler;
            // Setup our progress bar
            iToolStripProgressBarSubTask.Maximum = 10000;
            iToolStripProgressBarSubTask.Value = 0;
            // Kick it off
            await copy.Start();
            // How to check for error?
            // Rename our file as robocopy for all its goodness can't do that
            string copied = Path.GetDirectoryName(destinationPath) + "\\" + Path.GetFileName(sourcePath);
            if (copied != destinationPath)
            {
                File.Move(copied, destinationPath);
            }            
        }

It's being use in a basic Windows form application. Closing the application using the form X button does not kill the robocopy process. Maybe it has to do with the fact I'm using all that async stuff.

**Comment by tjscience** [comment] 2018-09-07 14:38
It may be the async stuff, but generally, any process that is started by an application should be killed when that application closes. Can you add copy.Stop() to an Exit or Shutdown event and see if that fixes it? Really, you should be properly disposing the robocopy process by calling RoboCommand.Stop() somewhere.

**Comment by bruceburge** [comment] 2018-09-15 03:59
@Slion I am trying to understand what you are attempting to do in your code you've posted here.  Specifically the if statement at the end.

Let sourcePath = @"Z:\Users\Bruce\Desktop\somefile.txt";
Let destinationPath = @"Z:\Users\Bruce\Desktop\";

the the code 
`        // Rename our file as robocopy for all its goodness can't do that
        string copied = Path.GetDirectoryName(destinationPath) + "\\" + Path.GetFileName(sourcePath);
        if (copied != destinationPath)
        {
            File.Move(copied, destinationPath);
        }  
`
copied = "Z:\Users\Bruce\Desktop\temp\somefile.txt"
destinationPath = "Z:\Users\Bruce\Desktop\temp\"
the equality will be false
your File.Move will be 
`File.Move(@"Z:\Users\Bruce\Desktop\temp\somefile.txt", @"Z:\Users\Bruce\Desktop\temp\"); `
will result 'System.IO.IOException' in mscorlib.dll
File move requires full paths for both. source and destination. 

I personally would recommend doing something similar to

```
if (Directory.Exists(destinationPath))
            {
                using (RoboSharp.RoboCommand robo = new RoboSharp.RoboCommand())
                {
                    // events                        
                    robo.OnCommandCompleted += Robo_OnCommandCompleted;
                    robo.OnCommandError += Robo_OnCommandError;
                    robo.OnError += Robo_OnError;
                    // copy options
                    robo.CopyOptions.Source = sourcePath;
                    robo.CopyOptions.Destination = destinationPath;
                    robo.CopyOptions.CopySubdirectoriesIncludingEmpty = true;
                    robo.CopyOptions.UseUnbufferedIo = true;
                    // select options
                    robo.SelectionOptions.OnlyCopyArchiveFilesAndResetArchiveFlag = false;
                    // prevent overwrite
                    robo.SelectionOptions.ExcludeChanged = true;
                    robo.SelectionOptions.ExcludeNewer = true;
                    robo.SelectionOptions.ExcludeOlder = true;
                    // retry options
                    robo.RetryOptions.RetryCount = 1;
                    robo.RetryOptions.RetryWaitTime = 2;
                    robo.Start()?.ContinueWith((p) =>
                    {
                        if (robo != null)
                        {
                            robo.OnCommandCompleted -= Robo_OnCommandCompleted;
                            robo.OnCommandError -= Robo_OnCommandError;
                            robo.OnError -= Robo_OnError;
                        }
                    });
                }
            }
            else
            {
                throw new DirectoryNotFoundException($" Destination directory  [{destinationPath}]");
            }
```
The robocommand implements IDisposable so either dispose of it, or better yet wrap it in a using and let the .net do it. 

There are several event handlers available from robo, and if you want to be safe, you should when done, unhook them.

I hope that helps.

**Comment by wingers999** [comment] 2020-02-19 23:28
@bernatpi @tjscience - suggest we perhaps close this as cannot replicate the problem, and have had no further feedback since 2018?

**Comment by bernatpi** [comment] 2020-02-20 08:26
@wingers999 - Sure. Closing it right now.

**Closed by bernatpi** 2020-02-20 08:26 UTC
